# Openfeign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  
# Sentry DSN
sentry:
  dsn: "{cipher}469414d181b92d00880c16588a8e5298ce5b0791e6b0252881bdc5b80332b2de890e6520f443379b1d70df74825640b89c4c9318a93d7545ea39c38a96f170940ff87f221c53367f3334d19311ae75381ca407f8e8a27f35ed9dca326efce5bb18dc981787630665ee5577f305b67017"
  send-default-pii: true